name: Build

on:
  push:
    paths:
      - "**.gradle"
      - "**.properties"
      - "**.java"
      - "**.xml"
      - ".github/workflows/*.yml"
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  fullbuild:
    runs-on: ubuntu-latest

    name: Java 8 build
    steps:
      - uses: actions/checkout@v2

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository'
            ~/.sonar/cache'
            ~/.gradle/caches/'
            ~/.gradle/wrapper/'
          key: ${{ runner.os }}-mvn_sonar_gradle_cache

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Install D-BUS AT-SPI core
        run: sudo apt-get -y install at-spi2-core

      - name: Check Java Directory
        run: echo $JAVA_HOME

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Build
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./gradlew build

      - name: Gradle SonarQube Scan
        if: ${{!github.event.pull_request.head.repo.fork}}
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            echo ${{ github.event.push.repository.fork }}
            ./gradlew sonarqube

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


