name: Create release

on:
  push:
    tags-ignore:
      - '*SNAPSHOT*'

jobs:
  create_release:
    name: Release
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path:
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run jpackage
        run: ./gradlew -Prelease=true jpackage
      - name: Zip package
        uses: TheDoctor0/zip-release@0.6.0
        with:
          type: 'zip'
          filename: utiLITI-${{ runner.os }}.zip
          directory: build/litiengine-utiliti/jpackage/
      - name: Upload asset to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/litiengine-utiliti/jpackage/utiLITI-${{ runner.os }}.zip
