name: Create release

on:
  push:
    # We don't want to publish for snapshot builds
    tags-ignore:
      - '*SNAPSHOT*'

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Extract version number
        id: tag_version
        shell: bash
        run: |
          echo ::set-output name=release_version::$(echo ${{github.ref_name}} | sed "s/^.*v\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\)-.*$/\1/")
      - name: Add release message
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.tag_version.outputs.release_version }}
          body: |
            <details>
              <summary>
              This version of LITIENGINE is available through [Maven Central](https://search.maven.org/artifact/de.gurkenlabs/litiengine):
              </summary>

              ### Gradle (Groovy)
              ````groovy
              implementation 'de.gurkenlabs:litiengine:${{ steps.tag_version.outputs.release_version }}'
              ````
              ### Gradle (Kotlin)
              ````kotlin
              implementation("de.gurkenlabs:litiengine:${{ steps.tag_version.outputs.release_version }}")
              ````
              ### Maven
              ````xml
              <dependency>
                <groupId>de.gurkenlabs</groupId>
                <artifactId>litiengine</artifactId>
                <version>${{ steps.tag_version.outputs.release_version }}</version>
              </dependency>
              ````
            </details>
  create_release_assets:
    name: Create release assets
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path:
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run jpackage
        run: ./gradlew -Prelease=true jpackage
      - name: Zip package
        uses: TheDoctor0/zip-release@0.6.0
        with:
          type: 'zip'
          filename: utiLITI-${{ runner.os }}.zip
          directory: build/litiengine-utiliti/jpackage/
      - name: Upload asset to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/litiengine-utiliti/jpackage/utiLITI-${{ runner.os }}.zip
